name: connect
version: 0.0.1
author: Jason Rowland <jasonxrowland@gmail.com>
description: A server middleware library for dart
homepage: https://github.com/jsonxr/dart-connect
environment:
  sdk: '>=0.5.7'
dependencies:
  args: any
  crypto: any
  logging: any
  meta: any
  mongo_dart: any
  route: any
  uuid: any
dev_dependencies:
  unittest: any
